# Docker file for a slim Ubuntu-based Python3 image

FROM centos:8

LABEL maintainer="Christopher Moussa <moussa1@llnl.gov>"

# add flux-accounting/ to src/ in container
ADD . src/

RUN yum -y update \
  && yum install -y python3-pip python3-devel git \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --user --upgrade pip

# go into flux-accounting, install dependencies, and run unit tests
RUN cd src/ \
  && pip3 install --user -r requirements.txt \
  && python -m unittest discover -b
