# Docker file for a slim Ubuntu-based Python3 image

FROM ubuntu:latest

LABEL maintainer="Christopher Moussa <moussa1@llnl.gov>"

# add flux-accounting/ to src/ in container
ADD . src/

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev git \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip \
  && pip3 install tox

# go into flux-accounting, install dependencies, and run unit tests
RUN cd src/ \
  && pip3 install -r requirements.txt \
  && tox
